### ISSUE TITLE
save/restore layout and preference 

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta#2]
User feedback from Toby Brown:

> 
Hi,

My installation of CARTA on the sever does not save layouts and preferences from one instance to the next. Can this be fixed?

Cheers
Toby

**Comment by kswang1029** [comment]
Hi Toby,

Thank you for sending us an issue report.

To understand the problem more, could you provide more info?

1) which CARTA desktop version and which os build are you using? (e.g., ubuntu v1.2.1)
2) which OS and version are you using? (e.g., ubuntu 18.04 LTS)
3) how do you launch CARTA? For example, by "./CARTA.appImage --remote” or else?
4) if you use a browser to use CARTA, which browser (and version) are you using?

We will follow this issue at https://github.com/CARTAvis/carta/issues/2 so please reply us on the Github issue directly. 

Again, thank you for reporting an issue. :)

Cheers
Kuo-Song

**Comment by drtobybrown** [comment]
For 1. and 2., I get the following on our server  (I don't *think* I'm running CARTA desktop):

```
# ~
# astro $ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.7.1908 (Core)
Release:	7.7.1908
Codename:	Core

# ~
# astro $ ls /mnt/astro/astro/local/carta
1.2.1/	current@
```

3. I start carta using the following command which I believe was set up by our computing support:

```
# ~
# astro $ carta
Starting CARTA in remote mode
 
To access CARTA, please enter either of the following URLs in your local web browser: 
 
astro:37028/?socketUrl=ws://astro:36816
 
OR
 
10.113.174.13:37028/?socketUrl=ws://10.113.174.13:36816
 
 
Press q to close CARTA:
```

4. On my local machine (MacOS 10.15.2) I'm using Firefox 72.0.1 (64-bit)

**Comment by veggiesaurus** [comment]
Ok, I think I see what's going on here. 

CARTA uses the browser's [local storage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) to store user preferences and layouts. For CARTA 1.3, we will also allow users to save preferences on a server-side database, if it is configured in an appropriate server setup. However, it appears that you are simply running "remote" CARTA, rather than a server setup, which would allow you to always access CARTA at a specific URL (but would require a bit more work on your computing support team) and use your normal login details to authenticate. 

The issue is that local storage is a per-origin setting, so each time you redirect your browser to a different URL or port, you're starting with a blank set of preferences, because your browser's origin is different. The only real solution to this is to ask your computing support team to install a CARTA server at a dedicated URL (We'd be happy to help with this, if needed).

**Comment by veggiesaurus** [comment]
There might be a slightly more hacky, but easier, solution: As long as the CARTA _frontend_ is delivered by the same location each time, the _backend_ can be located on any IP and port. So for example, if your computing support staff made the CARTA frontend available at `carta.astro.mydomain.ca`, then you could use a URL such as 

`carta.astro.mydomain.ca?socketUrl=ws://10.113.174.13:36816 `

That way, the frontend would always be delivered by the same origin, and your settings would persist.  @kswang1029 @ajm-asiaa  perhaps we should consider such a model for remote users in 1.3 to get around this issue (e.g. instead of spinning up a frontend server, if the remote version is configured to use a specific frontend URL, then it would generate a URL based on that URL, rather than a local HTTP server

**Comment by toddpfaff** [comment]
I'm the "computing support" that Toby refers to above.  Toby brought this issue to my attention earlier today.  I had installed CARTA Remote version 1.2.2 for Toby but I wasn't aware there was also a CARTA "server" that may be required.  In what situations is the server required?  Does the CARTA server replace CARTA Remote or is it installed in addition to what we already have installed.  I'm happy to try the server if it's needed for Toby's use case and it doesn't take too much effort.  Is the server installation documented?

I don't understand what is being suggested as the "hacky" solution above.  How can what you're suggesting be done?  When we run CARTA, it chooses random ports and tells us what URL to use.

If I run "carta --help" I see that it takes options "--port" and "--fport" which allow the otherwise random ports to be specified.  If Toby were to specify these options when he runs CARTA, would that get around the problem he is encountering with the URL being different each time (due to the randomly selected ports)?  Is this essentially what is being suggested above as the hacky solution?

Thanks,
Todd

**Comment by veggiesaurus** [comment]
Thanks for the info and suggestions, Todd :+1: 

> In what situations is the server required? Does the CARTA server replace CARTA Remote or is it installed in addition to what we already have installed. I'm happy to try the server if it's needed for Toby's use case and it doesn't take too much effort. Is the server installation documented?

The server deployment is designed to allow all users on a system access CARTA from a dedicated URL, with the CARTA backend process started as their unix user (using Apache's su-exec). It is somewhat documented [here](https://github.com/CARTAvis/carta-server), but we'd be happy to help you through the process in more detail if you're willing to put in the time.

> I don't understand what is being suggested as the "hacky" solution above. How can what you're suggesting be done? When we run CARTA, it chooses random ports and tells us what URL to use.

If you serve the frontend component of CARTA separately on a dedicated URL (it's just a collection of static files), then Toby will replace the first part of the URL with the dedicated URL, rather than the local HTTP server's address. 

> If I run "carta --help" I see that it takes options "--port" and "--fport" which allow the otherwise random ports to be specified. If Toby were to specify these options when he runs CARTA, would that get around the problem he is encountering with the URL being different each time (due to the randomly selected ports)? Is this essentially what is being suggested above as the hacky solution?

If he's always firing up CARTA from the same host, then I think that will solve the issue, since the port and the host name will be the same. This would be the simplest solution.

**Comment by drtobybrown** [comment]
>>     If I run "carta --help" I see that it takes options "--port" and "--fport" which allow the otherwise random ports to be specified. If Toby were to specify these options when he runs CARTA, would that get around the problem he is encountering with the URL being different each time (due to the randomly selected ports)? Is this essentially what is being suggested above as the hacky solution?
> 
> If he's always firing up CARTA from the same host, then I think that will solve the issue, since the port and the host name will be the same. This would be the simplest solution.

Great, thanks all. This works.
