### ISSUE TITLE
subpixel region spectra don't work if region crosses pixel boundary

### ISSUE THREAD

**Issue by teuben** [CARTAvis/carta#24]
I happen to have a small 14 x 14 pixel x 2048 cube, so i wind up looking at spectra per pixel. So I zoom in, select a small region so it's clearly inside one pixel. That works fine, but as soon as you then cross a boundary to the next pixel, the spectrum is blank. no data.

It also seems that only the center of my little box is used to probe the cube. Or another way of saying: if the center of a pixel is inside the box, it's counted. It doesn't do any area weighting if the area covers a partial pixel. I can forgive CARTA for that, I doubt this has any practical application, and is likely quite expensive for larger boxes.

**Comment by veggiesaurus** [comment]
> It also seems that only the center of my little box is used to probe the cube. Or another way of saying: if the center of a pixel is inside the box, it's counted.

@teuben this is done in order to produce identical results to CASA and casaviewer. DS9 has a similar approach:

![image](https://user-images.githubusercontent.com/592504/81935078-56d96980-95f0-11ea-839c-3923735143b5.png)

![image](https://user-images.githubusercontent.com/592504/81935238-9d2ec880-95f0-11ea-9e0a-1a2e84c290fc.png)


> I doubt this has any practical application, and is likely quite expensive for larger boxes.

I think the one practical application it _does_ have is avoiding the confusing situation you've described above, where a region that has finite size ends up containing zero pixels. 

I'm not sure what the appropriate solution is, though. We've aimed for consistency across the different region types, where pixels are in a region of any shape if and only if their center is contained within the region.

@kswang1029 I know we talked about weighting at one stage, but I don't think CASA supports that, does it?

**Comment by teuben** [comment]
I appreciate that legacy applications are reproducable. The blank spectrum was a bit of a surprise to me. I reproduced this "feature" in ds9. I guess we don't often work on the pixel level.

In light of this, I would mark this issue as "done for now" or so.   I suspect observers would agree an not care about this corner case. Theory people might raise the eyebrow a little higher.

**Comment by kswang1029** [comment]
astropy supports sub-pixel treatment. 

Possible use case would be comparing spectral profiles from spatially and spectrally matched cubes with very different pixel sizes.

**Comment by veggiesaurus** [comment]
> Theory people might raise the eyebrow a little higher.

As someone who was not originally familiar with legacy applications, I found this rather confusing, because I expected applications to weight things properly. But this does get a little tricky with partial coverage in polygons

**Comment by kswang1029** [comment]
ps there is no sub pixel thing in CASA
