### ISSUE TITLE
Feature request: start up with multiple images via a single URL

### ISSUE THREAD

**Issue by o-smirnov** [CARTAvis/carta#68]
Is there full documentation for the URL options somewhere? I know how to open CARTA up with an image pre-loaded using the ``&folder=foo&file=bar.fits`` trick (as discussed in https://carta.readthedocs.io/en/latest/installation_and_configuration.html#command-line-startup), but what if I'd like to load multiple images, can I specify that via the URL?

**Comment by veggiesaurus** [comment]
This will be handled in 2.0. backend support for this is already in place, we just need a minor front-end adjustment

**Comment by o-smirnov** [comment]
Thanks @veggiesaurus. How is this implemented -- ``?files=file1,file2`` as discussed somewhere in the linked issues? I'm having trouble finding the URL options in the current documentation.

**Comment by veggiesaurus** [comment]
> Thanks @veggiesaurus. How is this implemented -- `?files=file1,file2` as discussed somewhere in the linked issues? I'm having trouble finding the URL options in the current documentation.

The URL file parameter was initially just a debug thing, and we were a bit caught off guard as to how popular it would be. That's why it's not documented properly. @kswang1029 can add some stuff to the user manual for the next (beta) release. This feature has been merged into dev, so it will make it into 3.0-beta.1 scheduled for early August.

You can use `files=file1,file2` or `files=[file1,file2]` if that looks more readable to you. You can also combine this with the `folder` parameter, or specify the folders explicitly. For example:

`http://localhost:3000/?files=[fits/wcs_dev_images/C.fits,fits/wcs_dev_images/C_GAL.fits]`
and
`http://localhost:3000/?folder=fits/wcs_dev_images&files=[C.fits,C_GAL.fits]`
are equivalent. 

Finally, you can also use the HDU number as a suffix (à la cfitsio file input) to specify that. For example. `file=C.fits[3]`. We will hopefully support the HDU/extension _name_ as well in future.

**Comment by o-smirnov** [comment]
Great stuff, thanks!
