### ISSUE TITLE
2.0-beta brew install fails on MacOS 11.2 BigSur

### ISSUE THREAD

**Issue by drtobybrown** [CARTAvis/carta#77]
```
# mbp $ brew install cartavis/tap/carta-beta
Error: 
  homebrew-core is a shallow clone.
  homebrew-cask is a shallow clone.
To `brew update`, first run:
  git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core fetch --unshallow
  git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask fetch --unshallow
These commands may take a few minutes to run due to the large size of the repositories.
This restriction has been made on GitHub's request because updating shallow
clones is an extremely expensive operation due to the tree layout and traffic of
Homebrew/homebrew-core and Homebrew/homebrew-cask. We don't do this for you
automatically to avoid repeatedly performing an expensive unshallow operation in
CI systems (which should instead be fixed to not use shallow clones). Sorry for
the inconvenience!
==> Installing carta-beta from cartavis/tap
==> Downloading https://github.com/CARTAvis/homebrew-tap/releases/download/carta-beta-2.0.0-beta.0/carta-beta-2.
Already downloaded: /Users/thbrown/Library/Caches/Homebrew/downloads/5b5ab11526f5d34a4dd1c54bd4d347594a47165d6736a277d992c2cda8ed7bcb--carta-beta-2.0.0-beta.0.catalina.bottle.1.tar.gz
==> Pouring carta-beta-2.0.0-beta.0.catalina.bottle.1.tar.gz
Warning: cartavis/tap/carta-beta dependency gcc was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.
🍺  /usr/local/Cellar/carta-beta/2.0.0-beta.0: 99 files, 22.7MB

# ~
# mbp $ carta
dyld: Library not loaded: /usr/local/opt/grpc/lib/libgrpc++.1.37.dylib
  Referenced from: /usr/local/bin/carta_backend
  Reason: image not found
/usr/local/bin/carta: line 13:  7576 Abort trap: 6           carta_backend "$@"
```

**Comment by ajm-ska** [comment]
@drtobybrown I am not able to reproduce the problem here, but did you try running:
`git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core fetch --unshallow`
`git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask fetch --unshallow`
Then:
`brew uninstall cartavis/tap/carta-beta`
`brew install cartavis/tap/carta-beta` 
?

I know it appears to be downloading the catalina bottle (Catalina is macOS 10.15), but it does that for my Big Sur 11.3 system too, and everything seems to work fine.

Something else to try is: `brew reinstall grpc`

If the above ideas don't work, another thing you could try is to install the formula from source (You may need to update your Xcode and Command Line Tools first. Homebrew will say so if you need to.):
`brew install --build-from-source cartavis/tap/carta-beta`

**Comment by drtobybrown** [comment]
Sorry, I accidentally unsubscribed so missed this. 

> @drtobybrown I am not able to reproduce the problem here, but did you try running:
> git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core fetch --unshallow
> git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask fetch --unshallow
> Then:
> brew uninstall cartavis/tap/carta-beta
> brew install cartavis/tap/carta-beta
> ?

This worked for me

**Comment by veggiesaurus** [comment]
@ajm-asiaa @drtobybrown can we close this?

**Comment by drtobybrown** [comment]
Yes.
