### ISSUE TITLE
Backend launcher fix #890 needs to be applied to appimage launcher

### ISSUE THREAD

**Issue by confluence** [CARTAvis/carta#91]
The `carta` launcher issue which was fixed in [#890](https://github.com/CARTAvis/carta-backend/pull/890) is still present in the latest beta appimage for Ubuntu (as reported [here](https://github.com/idia-astro/carta-python/issues/22)).

**Comment by ajm-ska** [comment]
OK. Since the beginning, AppImages have always used their own launcher script. This was well before the `scripts/carta` launcher script existed. So that is why any fixes are not present in the latest beta AppImage, simply because it doesn't use the script. I'll make sure to incorporate what it does in future AppImage releases.

**Comment by ajm-ska** [comment]
I have just checked on a pre-v3.0.0-beta3 AppImage. We have now added the relevant lines from `scripts/carta` into the AppImage's `AppRun` script:

```
FIRST_IP=$(hostname -I | cut -d' ' -f1)
# Only export env variable if it's not empty
if [ ! -z $FIRST_IP ]; then
    export SERVER_IP=$FIRST_IP
fi
```
(AppImages only run on Linux, so we don't need to check whether it is Darwin or Linux)

This problem will not appear in any future releases.
